<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $des = "Fugiat eveniet enim in. Id ipsa laboriosam nihil quod tempore quaerat. Quasi qui aperiam ratione ea quos consectetur. Hic maxime consequatur vel maiores autem voluptas.";
        //Factory to Generate 5 Product
        DB::table('products')->insert([
            [
                'p_name' => 'Headphones Smart',
                'p_slug' =>  'Headphones-Smart',
                'p_description' => $des,
                'p_image_1' => 'products-img/Headphones-1.webp',
                'p_image_2' => 'products-img/Headphones-2.webp',
                'p_image_3' => 'products-img/Headphones-3.webp',
                'p_image_4' => 'products-img/Headphones-4.webp',
                'p_color' => 'White',
                'p_price' => 200,
                'category_id' => 8,
                'user_id' => 1,
                'created_at' =>  '2022-04-01',
                'updated_at' =>  '2022-04-01',
            ],
            [
                'p_name' => 'Headphones Hot',
                'p_slug' =>  'Headphones-Hot',
                'p_description' => $des,
                'p_image_1' => 'products-img/casc-1.webp',
                'p_image_2' => 'products-img/casc-2.webp',
                'p_image_3' => 'products-img/casc-3.webp',
                'p_image_4' => 'products-img/casc-4.webp',
                'p_color' => 'Black',
                'p_price' => 300,
                'category_id' => 8,
                'user_id' => 1,
                'created_at' => '2022-04-02',
                'updated_at' =>  '2022-04-02',
            ],
            [
                'p_name' => 'airpods',
                'p_slug' =>  'airpods',
                'p_description' => $des,
                'p_image_1' => 'products-img/airpods-1.webp',
                'p_image_2' => 'products-img/airpods-2.webp',
                'p_image_3' => 'products-img/airpods-3.webp',
                'p_image_4' => 'products-img/airpods-4.webp',
                'p_color' => 'Green',
                'p_price' => 150,
                'category_id' => 8,
                'user_id' => 1,

                'created_at' => '2022-04-03',
                'updated_at' =>  '2022-04-03',
            ],
            [
                'p_name' => 'backbag Semple',
                'p_slug' =>  'backbag-Semple',
                'p_description' => $des,
                'p_image_1' => 'products-img/backbag-1.webp',
                'p_image_2' => 'products-img/backbag-2.webp',
                'p_image_3' => 'products-img/backbag-3.webp',
                'p_image_4' => 'products-img/backbag-4.webp',
                'p_color' => 'Green',
                'p_price' => 100,
                'category_id' => 7,
                'user_id' => 1,

                'created_at' => Carbon::now(),
                'updated_at' =>  Carbon::now(),
            ],
            [
                'p_name' => 'camera Smart',
                'p_slug' =>  'camera-Smart',
                'p_description' => $des,
                'p_image_1' => 'products-img/camera-1.webp',
                'p_image_2' => 'products-img/camera-2.webp',
                'p_image_3' => 'products-img/camera-3.webp',
                'p_image_4' => 'products-img/camera-4.webp',
                'p_color' => 'Black',
                'p_price' => 1400,
                'category_id' => 5,
                'user_id' => 1,

                'created_at' => Carbon::now(),
                'updated_at' =>  Carbon::now(),
            ],
            [
                'p_name' => 'camera Hot',
                'p_slug' =>  'camera-Hot',
                'p_description' => $des,
                'p_image_1' => 'products-img/cameraa-1.webp',
                'p_image_2' => 'products-img/cameraa-2.webp',
                'p_image_3' => 'products-img/cameraa-3.webp',
                'p_image_4' => 'products-img/cameraa-4.webp',
                'p_color' => 'Black',
                'p_price' => 1000,
                'category_id' => 5,
                'user_id' => 1,

                'created_at' => Carbon::now(),
                'updated_at' =>  Carbon::now(),
            ],
            [
                'p_name' => 'Perfume-Hot',
                'p_slug' =>  'Perfume-Hot',
                'p_description' => $des,
                'p_image_1' => 'products-img/Perfume-1.webp',
                'p_image_2' => 'products-img/Perfume-2.webp',
                'p_image_3' => 'products-img/Perfume-3.webp',
                'p_image_4' => 'products-img/Perfume-4.webp',
                'p_color' => 'non',
                'p_price' => 450,
                'category_id' => 3,
                'user_id' => 1,

                'created_at' => Carbon::now(),
                'updated_at' =>  Carbon::now(),
            ],
            [
                'p_name' => 'Perfume normal',
                'p_slug' =>  'Perfume-normal',
                'p_description' => $des,
                'p_image_1' => 'products-img/rihaa-1.webp',
                'p_image_2' => 'products-img/rihaa-2.webp',
                'p_image_3' => 'products-img/rihaa-3.webp',
                'p_image_4' => 'products-img/rihaa-4.webp',
                'p_color' => 'non',
                'p_price' => 320,
                'category_id' => 3,
                'user_id' => 1,

                'created_at' => Carbon::now(),
                'updated_at' =>  Carbon::now(),
            ],
            [
                'p_name' => 'phon xs',
                'p_slug' =>  'phon-xs',
                'p_description' => $des,
                'p_image_1' => 'products-img/phon-1.webp',
                'p_image_2' => 'products-img/phon-2.webp',
                'p_image_3' => 'products-img/phon-3.webp',
                'p_image_4' => 'products-img/v-4.webp',
                'p_color' => 'Reed',
                'p_price' => 1000,
                'category_id' => 1,
                'user_id' => 1,

                'created_at' => Carbon::now(),
                'updated_at' =>  Carbon::now(),
            ],
            [
                'p_name' => 'shoess hot',
                'p_slug' =>  'shoess-hot',
                'p_description' => $des,
                'p_image_1' => 'products-img/sbrdila-1.webp',
                'p_image_2' => 'products-img/sbrdila-2.webp',
                'p_image_3' => 'products-img/sbrdila-3.webp',
                'p_image_4' => 'products-img/sbrdila-4.webp',
                'p_color' => 'White',
                'p_price' => 540,
                'category_id' => 4,
                'user_id' => 1,

                'created_at' => '2022-04-05',
                'updated_at' =>  '2022-04-05',
            ],
            [
                'p_name' => 'shoess new',
                'p_slug' =>  'shoess-new',
                'p_description' => $des,
                'p_image_1' => 'products-img/shoes-1.webp',
                'p_image_2' => 'products-img/shoes-2.webp',
                'p_image_3' => 'products-img/shoes-3.webp',
                'p_image_4' => 'products-img/shoes-4.webp',
                'p_color' => 'Black',
                'p_price' => 430,
                'category_id' => 4,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' =>  Carbon::now(),
            ],
            [
                'p_name' => 'shoes prfect',
                'p_slug' =>  'shoes-prfect',
                'p_description' => $des,
                'p_image_1' => 'products-img/shoess-1.jpg',
                'p_image_2' => 'products-img/shoess-2.jpg',
                'p_image_3' => 'products-img/shoess-3.jpg',
                'p_image_4' => 'products-img/shoess-4.jpg',
                'p_color' => 'White',
                'p_price' => 460,
                'category_id' => 4,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' =>  Carbon::now(),
            ],
            [
                'p_name' => 'new watch',
                'p_slug' =>  'new-watch',
                'p_description' => $des,
                'p_image_1' => 'products-img/watcha-1.jpg',
                'p_image_2' => 'products-img/watcha-2.jpg',
                'p_image_3' => 'products-img/watcha-3.jpg',
                'p_image_4' => 'products-img/watcha-4.jpg',
                'p_color' => 'Black and white',
                'p_price' => 200,
                'category_id' => 6,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' =>  Carbon::now(),
            ],
            [
                'p_name' => 'Prefect watch ',
                'p_slug' =>  'Prefect-watch',
                'p_description' => $des,
                'p_image_1' => 'products-img/watch-1.jpg',
                'p_image_2' => 'products-img/watch-2.jpg',
                'p_image_3' => 'products-img/watch-3.jpg',
                'p_image_4' => 'products-img/watch-4.jpg',
                'p_color' => 'Black and white',
                'p_price' => 200,
                'category_id' => 6,
                'user_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' =>  Carbon::now(),
            ],
        ]);
    }
}
